name: Grade Exam

on:
  push:
    branches: [ main ]

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: |
          g++ -std=c++20 \
          assignment/solution.cpp \
          grader/main.cpp \
          grader/reference.cpp \
          tests/public_tests.cpp \
          tests/hidden_tests.cpp \
          -o exam

      - name: Run
        run: ./exam
